blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/[TODO: GITHUB_ORG]/[TODO: REPO_NAME]#readme
    about: Check the README and docs before opening an issue
